export const PERMISSIONS = [
  "cms:read",
  "cms:write",
  "cms:publish",
  "leads:read",
  "leads:write",
  "products:read",
  "products:write",
  "orgs:read",
  "orgs:write",
  "orgs:verify",
  "users:read",
  "users:write",
  "users:disable",
  "roles:manage",
  "transactions:read",
  "transactions:write",
  "transactions:assign",
  "transactions:approve",
  "documents:read",
  "documents:write",
  "documents:approve",
  "documents:download",
  "messages:read",
  "messages:write",
  "finance:read",
  "finance:write",
  "finance:export",
  "shipments:read",
  "shipments:write",
  "shipments:approve",
  "bookings:read",
  "bookings:write",
  "ai:use",
  "ai:manage",
  "integrations:manage",
  "terms:manage",
  "audit:read",
  "settings:manage",
  "exports:run",
  "banking:review",
  "banking:select",
  "deal_groups:read",
  "deal_groups:write",
  "procurement:read",
  "procurement:write",
  "supplier:access",
  "buyer:access",
  "workspace:access",
  "admin:access",
  "security:read",
  "security:manage",
  "deployment:read",
  "deployment:approve",
  "uat:manage",
  "release:approve",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export type RoleKey =
  | "ceo_super_admin"
  | "general_manager"
  | "trade_manager"
  | "employee_operations"
  | "finance"
  | "compliance_reviewer"
  | "buyer_org_admin"
  | "buyer_member"
  | "supplier_org_admin"
  | "supplier_member"
  | "banking_advisor"
  | "readonly_auditor";

export const ROLE_PERMISSIONS: Record<RoleKey, Permission[]> = {
  ceo_super_admin: [...PERMISSIONS],
  general_manager: [
    "cms:read",
    "cms:write",
    "cms:publish",
    "leads:read",
    "leads:write",
    "products:read",
    "products:write",
    "orgs:read",
    "orgs:write",
    "orgs:verify",
    "users:read",
    "users:write",
    "users:disable",
    "roles:manage",
    "transactions:read",
    "transactions:write",
    "transactions:assign",
    "transactions:approve",
    "documents:read",
    "documents:write",
    "documents:approve",
    "documents:download",
    "messages:read",
    "messages:write",
    "finance:read",
    "finance:write",
    "finance:export",
    "shipments:read",
    "shipments:write",
    "shipments:approve",
    "bookings:read",
    "bookings:write",
    "ai:use",
    "ai:manage",
    "integrations:manage",
    "terms:manage",
    "audit:read",
    "settings:manage",
    "exports:run",
    "banking:select",
    "deal_groups:read",
    "deal_groups:write",
    "procurement:read",
    "procurement:write",
    "workspace:access",
    "admin:access",
  ],
  trade_manager: [
    "leads:read",
    "leads:write",
    "products:read",
    "orgs:read",
    "transactions:read",
    "transactions:write",
    "transactions:assign",
    "transactions:approve",
    "documents:read",
    "documents:write",
    "documents:approve",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
    "shipments:write",
    "shipments:approve",
    "bookings:read",
    "bookings:write",
    "deal_groups:read",
    "deal_groups:write",
    "procurement:read",
    "procurement:write",
    "finance:read",
    "banking:review",
    "banking:select",
    "ai:use",
    "workspace:access",
  ],
  employee_operations: [
    "leads:read",
    "products:read",
    "orgs:read",
    "transactions:read",
    "transactions:write",
    "documents:read",
    "documents:write",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
    "shipments:write",
    "shipments:approve",
    "bookings:read",
    "ai:use",
    "workspace:access",
  ],
  finance: [
    "transactions:read",
    "documents:read",
    "documents:download",
    "finance:read",
    "finance:write",
    "finance:export",
    "banking:review",
    "exports:run",
    "workspace:access",
  ],
  compliance_reviewer: [
    "orgs:read",
    "orgs:verify",
    "transactions:read",
    "procurement:read",
    "deal_groups:read",
    "documents:read",
    "documents:approve",
    "documents:download",
    "audit:read",
    "workspace:access",
  ],
  buyer_org_admin: [
    "buyer:access",
    "transactions:read",
    "transactions:write",
    "documents:read",
    "documents:write",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
  ],
  buyer_member: [
    "buyer:access",
    "transactions:read",
    "transactions:write",
    "documents:read",
    "documents:write",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
  ],
  supplier_org_admin: [
    "supplier:access",
    "transactions:read",
    "transactions:write",
    "procurement:read",
    "procurement:write",
    "documents:read",
    "documents:write",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
    "shipments:write",
  ],
  supplier_member: [
    "supplier:access",
    "transactions:read",
    "procurement:read",
    "documents:read",
    "documents:write",
    "documents:download",
    "messages:read",
    "messages:write",
    "shipments:read",
    "shipments:write",
  ],
  banking_advisor: [
    "banking:review",
    "transactions:read",
    "documents:read",
    "documents:download",
    "messages:read",
    "messages:write",
  ],
  readonly_auditor: [
    "audit:read",
    "transactions:read",
    "documents:read",
    "orgs:read",
    "workspace:access",
  ],
};

export function hasPermission(
  granted: Permission[] | undefined,
  required: Permission | Permission[] | string,
): boolean {
  if (!granted?.length) return false;
  const needed = Array.isArray(required) ? required : [required];
  return needed.every((p) => {
    const resolved = resolvePermissionAlias(p);
    return resolved ? granted.includes(resolved) : false;
  });
}

/** Dot-notation aliases from Phase 2 spec → internal colon permissions */
const PERMISSION_ALIASES: Record<string, Permission> = {
  "users.view": "users:read",
  "users.create": "users:write",
  "users.update": "users:write",
  "users.suspend": "users:disable",
  "roles.view": "roles:manage",
  "roles.assign": "roles:manage",
  "organizations.view": "orgs:read",
  "organizations.create": "orgs:write",
  "organizations.update": "orgs:write",
  "organizations.review": "orgs:verify",
  "organizations.approve": "orgs:verify",
  "organizations.reject": "orgs:verify",
  "organizations.suspend": "orgs:write",
  "invitations.create": "users:write",
  "invitations.revoke": "users:write",
  "kyb.view": "orgs:read",
  "kyb.submit": "buyer:access",
  "kyb.review": "orgs:verify",
  "kyb.request_changes": "orgs:verify",
  "kyb.approve": "orgs:verify",
  "kyb.reject": "orgs:verify",
  "terms.manage": "terms:manage",
  "audit.view": "audit:read",
  "settings.manage": "settings:manage",
  "buyer_requests.create": "transactions:write",
  "buyer_requests.view_own": "transactions:read",
  "buyer_requests.review": "transactions:approve",
  "buyer_requests.convert": "transactions:assign",
  "transactions.create": "transactions:write",
  "transactions.view_own": "transactions:read",
  "transactions.view_assigned": "transactions:read",
  "transactions.view_all": "transactions:read",
  "transactions.update_draft": "transactions:write",
  "transactions.submit": "transactions:write",
  "transactions.assign": "transactions:assign",
  "transactions.approve": "transactions:approve",
  "transactions.decline": "transactions:approve",
  "transactions.place_on_hold": "transactions:approve",
  "transactions.cancel": "transactions:approve",
  "commercial_terms.view": "transactions:read",
  "commercial_terms.edit": "transactions:write",
  "commercial_terms.approve": "transactions:approve",
  "specifications.view": "products:read",
  "specifications.manage": "products:write",
  "documents.create": "documents:write",
  "documents.upload": "documents:write",
  "documents.view": "documents:read",
  "documents.review": "documents:approve",
  "documents.approve": "documents:approve",
  "documents.request_changes": "documents:approve",
  "documents.reopen": "documents:write",
  "documents.send": "documents:write",
  "documents.sign": "documents:write",
  "documents.download": "documents:download",
  "templates.manage": "cms:write",
  "clauses.manage": "cms:write",
  "banking_instruments.select": "banking:select",
  "transaction_messages.create": "messages:write",
  "transaction_tasks.manage": "transactions:assign",
  "transaction_audit.view": "audit:read",
  "supplier_offers.create": "transactions:write",
  "supplier_offers.view_own": "transactions:read",
  "supplier_offers.review": "transactions:approve",
  "supplier_offers.convert": "transactions:assign",
  "procurement.create": "procurement:write",
  "procurement.view_own": "procurement:read",
  "procurement.view_assigned": "procurement:read",
  "procurement.view_all": "procurement:read",
  "procurement.update_draft": "procurement:write",
  "procurement.submit": "procurement:write",
  "procurement.assign": "transactions:assign",
  "procurement.approve": "transactions:approve",
  "procurement.decline": "transactions:approve",
  "procurement.place_on_hold": "transactions:approve",
  "procurement.cancel": "transactions:approve",
  "procurement_terms.view": "procurement:read",
  "procurement_terms.edit": "procurement:write",
  "procurement_terms.approve": "transactions:approve",
  "supplier_documents.create": "documents:write",
  "supplier_documents.upload": "documents:write",
  "supplier_documents.view": "documents:read",
  "supplier_documents.submit": "documents:write",
  "supplier_documents.review": "documents:approve",
  "supplier_documents.approve": "documents:approve",
  "supplier_documents.request_changes": "documents:approve",
  "supplier_documents.reopen": "documents:write",
  "supplier_documents.send": "documents:write",
  "supplier_documents.sign": "documents:write",
  "supplier_documents.download": "documents:download",
  "procurement_banking.select": "banking:select",
  "deal_groups.create": "deal_groups:write",
  "deal_groups.view": "deal_groups:read",
  "deal_groups.update": "deal_groups:write",
  "deal_groups.link": "deal_groups:write",
  "deal_groups.unlink": "deal_groups:write",
  "deal_groups.allocate": "deal_groups:write",
  "supplier_messages.create": "messages:write",
  "supplier_tasks.manage": "transactions:assign",
  "procurement_audit.view": "audit:read",
  "banking.view_own": "transactions:read",
  "banking.view_assigned": "banking:review",
  "banking.view_all": "banking:review",
  "banking.create": "banking:select",
  "banking.configure": "banking:select",
  "banking.select_instrument": "banking:select",
  "banking.update_draft": "banking:review",
  "banking.submit_review": "banking:review",
  "banking.review": "banking:review",
  "banking.approve_wording": "banking:review",
  "banking.record_issuance_request": "transactions:read",
  "banking.upload_issued_instrument": "banking:review",
  "banking.record_advice": "banking:review",
  "banking.record_authentication_evidence": "banking:review",
  "banking.compare_instrument": "banking:review",
  "banking.request_amendment": "banking:review",
  "banking.approve_amendment": "banking:review",
  "banking.record_presentation": "banking:review",
  "banking.record_bank_response": "banking:review",
  "banking.manage_discrepancy": "banking:review",
  "banking.record_waiver": "banking:review",
  "banking.record_honour": "banking:review",
  "banking.record_refusal": "banking:review",
  "banking.assign_adviser": "banking:review",
  "banking.manage_deadlines": "banking:review",
  "banking.manage_bank_parties": "banking:review",
  "banking.download_documents": "documents:download",
  "banking.audit.view": "audit:read",
  "shipments.create": "shipments:write",
  "shipments.view_own": "shipments:read",
  "shipments.view_assigned": "shipments:read",
  "shipments.view_all": "shipments:read",
  "shipments.update": "shipments:write",
  "shipments.assign": "shipments:write",
  "shipments.approve": "shipments:approve",
  "shipments.cancel": "shipments:approve",
  "shipment_schedules.manage": "shipments:write",
  "shipment_allocations.manage": "deal_groups:write",
  "freight_bookings.manage": "shipments:write",
  "inspection.create": "shipments:write",
  "inspection.update": "shipments:write",
  "inspection.review": "documents:approve",
  "document_checklists.create": "shipments:write",
  "document_checklists.request": "transactions:write",
  "document_checklists.review": "documents:approve",
  "document_checklists.approve": "shipments:approve",
  "document_checklists.lock": "shipments:approve",
  "shipping_documents.upload": "documents:write",
  "shipping_documents.view": "documents:read",
  "shipping_documents.review": "documents:approve",
  "shipping_documents.approve": "documents:approve",
  "shipping_documents.request_changes": "documents:approve",
  "shipping_documents.reopen": "documents:write",
  "shipping_documents.download": "documents:download",
  "presentation_packages.create": "shipments:write",
  "presentation_packages.review": "documents:approve",
  "presentation_packages.approve": "shipments:approve",
  "tracking.manage": "shipments:write",
  "tracking.view": "shipments:read",
  "customs.manage": "shipments:write",
  "delivery.manage": "shipments:write",
  "claims.create": "transactions:write",
  "claims.review": "shipments:approve",
  "claims.resolve": "shipments:approve",
  "shipment_audit.view": "audit:read",
  "finance.view_own": "finance:read",
  "finance.view_assigned": "finance:read",
  "finance.view_all": "finance:read",
  "finance.entries.create": "finance:write",
  "finance.entries.review": "finance:write",
  "finance.entries.approve": "finance:write",
  "finance.entries.post": "finance:write",
  "finance.entries.reverse": "finance:write",
  "finance.invoices.create": "finance:write",
  "finance.invoices.approve": "finance:write",
  "finance.invoices.issue": "finance:write",
  "finance.bills.create": "finance:write",
  "finance.bills.approve": "finance:write",
  "finance.bills.post": "finance:write",
  "finance.payments.record": "finance:write",
  "finance.payments.verify": "finance:write",
  "finance.payments.allocate": "finance:write",
  "finance.costs.manage": "finance:write",
  "finance.fees.manage": "finance:write",
  "finance.commissions.manage": "finance:write",
  "finance.taxes.manage": "finance:write",
  "finance.fx.manage": "finance:write",
  "finance.reports.view": "finance:read",
  "finance.reports.export": "finance:export",
  "finance.profitability.view": "finance:read",
  "finance.periods.close": "finance:write",
  "finance.accounting.configure": "finance:write",
  "finance.accounting.sync": "finance:write",
  "finance.audit.view": "audit:read",
  "integrations.view": "integrations:manage",
  "integrations.configure": "integrations:manage",
  "integrations.test": "integrations:manage",
  "integrations.enable": "integrations:manage",
  "integrations.disable": "integrations:manage",
  "integrations.logs.view": "integrations:manage",
  "ai.public.manage": "ai:manage",
  "ai.internal.use": "ai:use",
  "ai.documents.extract": "ai:use",
  "ai.documents.compare": "ai:use",
  "ai.documents.draft": "ai:use",
  "ai.outputs.review": "ai:manage",
  "ai.prompts.manage": "ai:manage",
  "ai.knowledge.manage": "ai:manage",
  "ai.usage.view": "ai:manage",
  "market_data.view": "finance:read",
  "market_data.configure": "integrations:manage",
  "market_alerts.manage": "finance:read",
  "esignature.create": "documents:write",
  "esignature.send": "documents:write",
  "esignature.view": "documents:read",
  "esignature.cancel": "documents:write",
  "screening.create": "orgs:verify",
  "screening.review": "orgs:verify",
  "screening.resolve": "orgs:verify",
  "shipping_integrations.manage": "integrations:manage",
  "accounting_integrations.manage": "finance:write",
  "notification_integrations.manage": "integrations:manage",
  "seo_ai.use": "cms:write",
  "social_drafts.manage": "cms:write",
  "security.dashboard.view": "security:read",
  "security.events.view": "security:read",
  "security.incidents.create": "security:manage",
  "security.incidents.manage": "security:manage",
  "security.sessions.revoke": "security:manage",
  "security.access_reviews.manage": "security:manage",
  "security.retention.manage": "security:manage",
  "security.legal_holds.manage": "security:manage",
  "security.backups.view": "security:read",
  "security.backups.verify": "security:manage",
  "security.settings.manage": "security:manage",
  "security.exports.manage": "security:manage",
  "deployment.view": "deployment:read",
  "deployment.approve": "deployment:approve",
  "uat.manage": "uat:manage",
  "release.approve": "release:approve",
};

export function resolvePermissionAlias(value: string): Permission | null {
  if ((PERMISSIONS as readonly string[]).includes(value)) return value as Permission;
  return PERMISSION_ALIASES[value] ?? null;
}

export function permissionsForRoles(roles: RoleKey[]): Permission[] {
  const set = new Set<Permission>();
  for (const role of roles) {
    for (const p of ROLE_PERMISSIONS[role] ?? []) set.add(p);
  }
  return [...set];
}
